global_costmap:
  global_frame: map
  robot_base_frame: human_human_base
  update_frequency: 10.0
  width: 40.0
  height: 40.0

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

