local_costmap:
  global_frame: map
  robot_base_frame: human2_human_base
  update_frequency: 3.0
  width: 3.0
  height: 3.0
  rolling_window: true
  origin_x: -5.0
  origin_y: -5.0
  robot_radius: 0.05

  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
