local_costmap:
  global_frame: map
  robot_base_frame: human_human_base
  update_frequency: 4.0
  width: 10.0
  height: 10.0
  rolling_window: true
  origin_x: -5.0
  origin_y: -5.0

  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

