publish_frequency: 5.0
update_frequency: 10.0
global_frame: map
robot_base_frame: base_link
rolling_window: false
robot_radius: 0.4
plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater, type: "costmap_2d::InflationLayer"}
  - {name: human_layer_static, type: "cohan_layers::StaticAgentLayer"}
  - {name: human_layer_visible, type: "cohan_layers::AgentVisibilityLayer"}

obstacles:
  observation_sources: base_scan_filtered
  base_scan_filtered: {data_type: LaserScan, topic: base_scan_filtered, expected_update_rate: 0.3, marking: true, clearing: true}
  footprint_clearing_enabled: true
  track_unknown_space: true
inflater:
  inflation_radius:     0.6  
  cost_scaling_factor:  9.0
static_map:
  enabled:              true
  map_topic:            "/map"
human_layer_static:
  robot_radius: 0.46
  agent_radius: 0.31
