controller_frequency: 4.0
recovery_behaviour_enabled: true

GlobalPlanner:
  allow_unknow: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  visualize_potential: false

  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 253

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 3
  acc_lim_y: 0
  acc_lim_th: 6

  max_vel_trans: 1.0
  min_vel_trans: 0.0

  max_vel_theta: 10.0
  min_vel_theta: 0.0

  max_vel_x: 1.0
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0


  # Goal Tolerance Parameters
  yaw_goal_tolerance: 3.1
  xy_goal_tolerance: 0.4
  latch_xy_goal_tolerance: false

  # # Forward Simulation Parameters
  sim_time: 4.0
  sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20
  penalize_negative_x: false

  # # Trajectory scoring parameters
  path_distance_bias: 32.0 # The weighting for how much the controller should stay close to the path it was given
  goal_distance_bias: 20.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  occdist_scale: 0.02 # The weighting for how much the controller should attempt to avoid obstacles
  # forward_point_distance: 0.325 # The distance from the center point of the robot to place an additional scoring point, in meters
  # stop_time_buffer: 0.2  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  # scaling_speed: 0.25 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  # max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by

  # # Oscillation Prevention Parameters
  # oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
