transform_tolerance: 0.8
sim_time: 1.7
sim_granularity: 0.025
dwa: true
vx_samples: 3
vtheta_samples: 20
goal_distance_bias: 0.8
path_distance_bias: 0.6
occdist_scale: 0.01
heading_lookahead: 0.325
oscillation_reset_dist: 0.05
acc_lim_th: 3.2
acc_lim_x: 2.5
acc_lim_y: 2.5
holonomic_robot: false
publish_traj_pc: true
publish_cost_grid_pc: true
