origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: true
transform_tolerance: 0.5
meter_scoring: true

#footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint_padding: 0.0

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  map_topic: /map
  subscribe_to_updates: true
  static_map: true

inflation_layer:
  enabled:              true
  inflation_radius:     1.75  # max. distance from an obstacle at which costs are incurred for planning paths.
  cost_scaling_factor:  2.58  # exponential rate at which the obstacle cost drops off (default: 10)
