origin_z: 0.0

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.5
meter_scoring: true

robot_radius: 0.37
footprint_padding: 0.0
publish_frequency: 3.0

static_layer:
  map_topic: /map
  subscribe_to_updates: true
  static_map: true

inflation_layer:
  enabled:              true
  inflation_radius:     0.6  # max. distance from an obstacle at which costs are incurred for planning paths.
  cost_scaling_factor:  6.0  # exponential rate at which the obstacle cost drops off (default: 10)


