global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 4.0
  width: 40.0
  height: 40.0

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
