controller_frequency: 20.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
max_planning_retries: 0

###############################################################

GlobalPlanner:
  allow_unknow: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  visualize_potential: false

  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 253

  orientation_mode: 0
  publish_potential: false

###############################################################

TebLocalPlannerROS:
  odom_topic: /human1/odom

 # Trajectory
  teb_autosize: true
  dt_ref: 0.2
  dt_hysteresis: 0.01
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 1.0
  feasibility_check_no_poses: 0
  global_plan_viapoint_sep: 0.1

  # Robot
  ## FAST ##
  #  max_vel_x: 2.0
  #  max_vel_x_backwards: 0.7
  #  max_vel_theta: 2.0
  #  max_vel_y: 1.5
  #  acc_lim_y: 2.0
  #  acc_lim_x: 4.0
  #  acc_lim_theta: 10.0
  ## SLOW ##
  max_vel_x: 0.7
  max_vel_x_backwards: 0.4
  max_vel_theta: 2.0
  max_vel_y: 0.5
  acc_lim_y: 2.0
  acc_lim_x: 4.0
  acc_lim_theta: 4.0

  min_turning_radius: 0.0
  wheelbase: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.30 # for type "circular"
    line_start: [-0.3, 0.0] # for type "line"
    line_end: [0.3, 0.0] # for type "line"
    front_offset: 0.2 # for type "two_circles"
    front_radius: 0.2 # for type "two_circles"
    rear_offset: 0.2 # for type "two_circles"
    rear_radius: 0.2 # for type "two_circles"
    vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

  # GoalTolerance

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  free_goal_vel: false

  # Obstacles

  min_obstacle_dist: 0.3
  inflation_dist: 1.0
  include_costmap_obstacles: true
  obstacle_association_force_inclusion_factor: 0.0
  obstacle_association_cutoff_factor: 1.0
  costmap_obstacles_behind_robot_dist: 0.4
  obstacle_poses_affected: 20
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5

  # Optimization

  no_inner_iterations: 4
  no_outer_iterations: 3
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.01
  weight_max_vel_x: 2
  weight_max_vel_y: 2
  weight_max_vel_theta: 0.5
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 0.9
  weight_kinematics_nh: 1.0
  weight_kinematics_forward_drive: 2.5
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_shortest_path: 1
  weight_obstacle: 0.3
  weight_dynamic_obstacle: 0.5
  selection_alternative_time_cost: false

  # Homotopy Class Planner

  enable_homotopy_class_planning: false
  enable_multithreading: true
  simple_exploration: false
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
