!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 0.4
  acc_lim_x: 0.3
  acc_lim_y: 0.3
  agent_acc_lim_theta: 0.8
  agent_acc_lim_x: 0.6
  agent_acc_lim_y: 0.3
  agent_pose_prediction_reset_time: 2.0
  agent_robot_ttc_scale_alpha: 1.0
  agent_robot_ttcplus_scale_alpha: 1.0
  allow_init_with_backwards_motion: false
  approach_angle: 3.14
  approach_angle_tolerance: 0.3
  approach_dist: 1.0
  approach_dist_tolerance: 0.2
  approach_id: 1
  cap_optimaltime_penalty: true
  cmd_angle_instead_rotvel: false
  costmap_obstacles_behind_robot_dist: 0.5
  disable_rapid_omega_chage: true
  disable_warm_start: true
  dt_hysteresis: 0.1
  dt_ref: 0.3
  dynamic_obstacle_inflation_dist: 0.6
  enable_multithreading: true
  exact_arc_length: false
  feasibility_check_no_poses: 2
  force_reinit_new_goal_angular: 0.78
  force_reinit_new_goal_dist: 1.0
  fov: 90.0
  free_goal_vel: true
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: 0.2
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          GoalTolerance: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              free_goal_vel: true
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 7
              name: GoalTolerance
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              xy_goal_tolerance: 0.2
              yaw_goal_tolerance: 0.1
            state: []
          HCPlanning: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              enable_multithreading: true
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              h_signature_prescaler: 0.5
              h_signature_threshold: 0.1
              id: 12
              max_number_classes: 4
              name: HCPlanning
              obstacle_heading_threshold: 0.45
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              roadmap_graph_area_length_scale: 1.0
              roadmap_graph_area_width: 5.0
              roadmap_graph_no_samples: 15
              selection_alternative_time_cost: false
              selection_cost_hysteresis: 1.0
              selection_obst_cost_scale: 2.0
              selection_prefer_initial_plan: 0.95
              selection_viapoint_cost_scale: 1.0
              state: true
              switching_blocking_period: 0.0
              type: ''
              viapoints_all_candidates: true
              visualize_hc_graph: true
            state: []
          Hateb_constraints: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              agent_pose_prediction_reset_time: 2.0
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                dictitems:
                  Approach: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      approach_angle: 3.14
                      approach_angle_tolerance: 0.3
                      approach_dist: 1.0
                      approach_dist_tolerance: 0.2
                      approach_id: 1
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 11
                      name: Approach
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 10
                      state: true
                      type: ''
                    state: []
                state: []
              id: 10
              min_agent_agent_dist: 0.2
              min_agent_robot_dist: 0.3
              name: Hateb_constraints
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              planning_mode: 1
              predict_agent_behind_robot: false
              predict_agent_goal: false
              rel_vel_cost_threshold: 2.0
              scale_agent_robot_ttc_c: false
              scale_agent_robot_ttcplus_c: false
              state: true
              ttc_threshold: 5.0
              ttcplus_threshold: 5.0
              ttcplus_timer: 1.0
              type: ''
              use_agent_agent_safety_c: true
              use_agent_elastic_vel: true
              use_agent_robot_rel_vel_c: false
              use_agent_robot_safety_c: true
              use_agent_robot_ttc_c: false
              use_agent_robot_ttcplus_c: false
              use_agent_robot_visi_c: false
              use_external_prediction: true
              visibility_cost_threshold: 2.5
            state: []
          Obstacles: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              costmap_obstacles_behind_robot_dist: 0.5
              dynamic_obstacle_inflation_dist: 0.6
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 8
              include_costmap_obstacles: true
              include_dynamic_obstacles: true
              inflation_dist: 0.6
              legacy_obstacle_association: false
              min_obstacle_dist: 0.2
              name: Obstacles
              obstacle_association_cutoff_factor: 5.0
              obstacle_association_force_inclusion_factor: 1.5
              obstacle_cost_mult: 1.0
              obstacle_poses_affected: 1
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              use_nonlinear_obstacle_penalty: true
            state: []
          Optimization: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              agent_robot_ttc_scale_alpha: 1.0
              agent_robot_ttcplus_scale_alpha: 1.0
              cap_optimaltime_penalty: true
              disable_rapid_omega_chage: true
              disable_warm_start: true
              fov: 90.0
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 9
              name: Optimization
              no_inner_iterations: 8
              no_outer_iterations: 4
              obstacle_cost_exponent: 1.0
              omega_chage_time_seperation: 1.0
              optimization_activate: true
              optimization_verbose: false
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              penalty_epsilon: 0.01
              state: true
              time_penalty_epsilon: 0.1
              type: ''
              weight_acc_lim_theta: 1.0
              weight_acc_lim_x: 1.0
              weight_acc_lim_y: 1.0
              weight_adapt_factor: 2.0
              weight_agent_acc_lim_theta: 2.0
              weight_agent_acc_lim_x: 2.0
              weight_agent_acc_lim_y: 2.0
              weight_agent_agent_safety: 2.0
              weight_agent_optimaltime: 3.0
              weight_agent_robot_rel_vel: 5.0
              weight_agent_robot_safety: 2.0
              weight_agent_robot_ttc: 1.0
              weight_agent_robot_ttcplus: 1.0
              weight_agent_robot_visibility: 5.0
              weight_agent_viapoint: 0.01
              weight_dynamic_obstacle: 50.0
              weight_dynamic_obstacle_inflation: 0.1
              weight_inflation: 0.1
              weight_kinematics_forward_drive: 1.0
              weight_kinematics_nh: 1.0
              weight_kinematics_turning_radius: 0.0
              weight_max_agent_vel_theta: 2.0
              weight_max_agent_vel_x: 4.0
              weight_max_agent_vel_y: 4.0
              weight_max_vel_theta: 1.0
              weight_max_vel_x: 2.0
              weight_max_vel_y: 2.0
              weight_nominal_agent_vel_x: 2.0
              weight_obstacle: 50.0
              weight_optimaltime: 1.0
              weight_shortest_path: 0.0
              weight_viapoint: 2.0
            state: []
          Other_Agents: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              agent_acc_lim_theta: 0.8
              agent_acc_lim_x: 0.6
              agent_acc_lim_y: 0.3
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 6
              max_agent_vel_theta: 1.1
              max_agent_vel_x: 1.3
              max_agent_vel_x_backwards: 0.01
              max_agent_vel_y: 0.4
              name: Other_Agents
              nominal_agent_vel_x: 1.1
              num_moving_avg: 5
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Recovery: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 13
              name: Recovery
              oscillation_recovery: true
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              shrink_horizon_backup: true
              state: true
              type: ''
            state: []
          Robot: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              acc_lim_theta: 0.4
              acc_lim_x: 0.3
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                dictitems:
                  Carlike: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      cmd_angle_instead_rotvel: false
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 4
                      min_turning_radius: 0.0
                      name: Carlike
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 3
                      state: true
                      type: ''
                      wheelbase: 1.0
                    state: []
                  Omnidirectional: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      acc_lim_y: 0.3
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 5
                      max_vel_y: 0.7
                      name: Omnidirectional
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 3
                      state: true
                      type: ''
                    state: []
                state: []
              id: 3
              is_footprint_dynamic: false
              is_real: false
              max_vel_theta: 1.2
              max_vel_x: 0.9
              max_vel_x_backwards: 0.6
              name: Robot
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Trajectory: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              allow_init_with_backwards_motion: false
              dt_hysteresis: 0.1
              dt_ref: 0.3
              exact_arc_length: false
              feasibility_check_no_poses: 2
              force_reinit_new_goal_angular: 0.78
              force_reinit_new_goal_dist: 1.0
              global_plan_overwrite_orientation: true
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              horizon_reduction_amount: 0.5
              id: 1
              max_global_plan_lookahead_dist: 1.0
              name: Trajectory
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              publish_feedback: false
              state: true
              teb_autosize: true
              teb_init_skip_dist: 0.4
              type: ''
              visualize_with_time_as_z_axis_scale: 0.0
            state: []
          ViaPoints: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              global_plan_viapoint_sep: 0.2
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              name: ViaPoints
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              via_points_ordered: false
            state: []
          Visualization: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 14
              name: Visualization
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              pose_array_z_scale: 0.5
              publish_agents_global_plans: true
              publish_agents_local_plan_fp_poses: true
              publish_agents_local_plan_poses: true
              publish_agents_local_plans: true
              publish_robot_global_plan: true
              publish_robot_local_plan: true
              publish_robot_local_plan_fp_poses: true
              publish_robot_local_plan_poses: true
              state: true
              type: ''
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  horizon_reduction_amount: 0.5
  include_costmap_obstacles: true
  include_dynamic_obstacles: true
  inflation_dist: 0.6
  is_footprint_dynamic: false
  is_real: false
  legacy_obstacle_association: false
  max_agent_vel_theta: 1.1
  max_agent_vel_x: 1.3
  max_agent_vel_x_backwards: 0.01
  max_agent_vel_y: 0.4
  max_global_plan_lookahead_dist: 1.0
  max_number_classes: 4
  max_vel_theta: 1.2
  max_vel_x: 0.9
  max_vel_x_backwards: 0.6
  max_vel_y: 0.7
  min_agent_agent_dist: 0.2
  min_agent_robot_dist: 0.3
  min_obstacle_dist: 0.2
  min_turning_radius: 0.0
  no_inner_iterations: 8
  no_outer_iterations: 4
  nominal_agent_vel_x: 1.1
  num_moving_avg: 5
  obstacle_association_cutoff_factor: 5.0
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_cost_exponent: 1.0
  obstacle_cost_mult: 1.0
  obstacle_heading_threshold: 0.45
  obstacle_poses_affected: 1
  omega_chage_time_seperation: 1.0
  optimization_activate: true
  optimization_verbose: false
  oscillation_recovery: true
  penalty_epsilon: 0.01
  planning_mode: 1
  pose_array_z_scale: 0.5
  predict_agent_behind_robot: false
  predict_agent_goal: false
  publish_agents_global_plans: true
  publish_agents_local_plan_fp_poses: true
  publish_agents_local_plan_poses: true
  publish_agents_local_plans: true
  publish_feedback: false
  publish_robot_global_plan: true
  publish_robot_local_plan: true
  publish_robot_local_plan_fp_poses: true
  publish_robot_local_plan_poses: true
  rel_vel_cost_threshold: 2.0
  roadmap_graph_area_length_scale: 1.0
  roadmap_graph_area_width: 5.0
  roadmap_graph_no_samples: 15
  scale_agent_robot_ttc_c: false
  scale_agent_robot_ttcplus_c: false
  selection_alternative_time_cost: false
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 2.0
  selection_prefer_initial_plan: 0.95
  selection_viapoint_cost_scale: 1.0
  shrink_horizon_backup: true
  switching_blocking_period: 0.0
  teb_autosize: true
  teb_init_skip_dist: 0.4
  time_penalty_epsilon: 0.1
  ttc_threshold: 5.0
  ttcplus_threshold: 5.0
  ttcplus_timer: 1.0
  use_agent_agent_safety_c: true
  use_agent_elastic_vel: true
  use_agent_robot_rel_vel_c: false
  use_agent_robot_safety_c: true
  use_agent_robot_ttc_c: false
  use_agent_robot_ttcplus_c: false
  use_agent_robot_visi_c: false
  use_external_prediction: true
  use_nonlinear_obstacle_penalty: true
  via_points_ordered: false
  viapoints_all_candidates: true
  visibility_cost_threshold: 2.5
  visualize_hc_graph: true
  visualize_with_time_as_z_axis_scale: 0.0
  weight_acc_lim_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_y: 1.0
  weight_adapt_factor: 2.0
  weight_agent_acc_lim_theta: 2.0
  weight_agent_acc_lim_x: 2.0
  weight_agent_acc_lim_y: 2.0
  weight_agent_agent_safety: 2.0
  weight_agent_optimaltime: 3.0
  weight_agent_robot_rel_vel: 5.0
  weight_agent_robot_safety: 2.0
  weight_agent_robot_ttc: 1.0
  weight_agent_robot_ttcplus: 1.0
  weight_agent_robot_visibility: 5.0
  weight_agent_viapoint: 0.01
  weight_dynamic_obstacle: 50.0
  weight_dynamic_obstacle_inflation: 0.1
  weight_inflation: 0.1
  weight_kinematics_forward_drive: 1.0
  weight_kinematics_nh: 1.0
  weight_kinematics_turning_radius: 0.0
  weight_max_agent_vel_theta: 2.0
  weight_max_agent_vel_x: 4.0
  weight_max_agent_vel_y: 4.0
  weight_max_vel_theta: 1.0
  weight_max_vel_x: 2.0
  weight_max_vel_y: 2.0
  weight_nominal_agent_vel_x: 2.0
  weight_obstacle: 50.0
  weight_optimaltime: 1.0
  weight_shortest_path: 0.0
  weight_viapoint: 2.0
  wheelbase: 1.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
state: []
